#!/usr/bin/env python3
"""Apply move mapping generated by build_mapping.py."""

from __future__ import annotations

import argparse
import csv
import json
import shutil
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root path")
    parser.add_argument("--mapping", default="ops/reorg/mapping.csv", help="Mapping CSV path")
    parser.add_argument("--mode", choices=["dry-run", "execute"], default="dry-run")
    parser.add_argument(
        "--report",
        default="ops/reorg/reports/apply_result.json",
        help="Apply report output path",
    )
    return parser.parse_args()


def unique_destination(path: Path) -> Path:
    if not path.exists():
        return path

    idx = 1
    while True:
        candidate = path.with_name(f"{path.stem}_dup{idx}{path.suffix}")
        if not candidate.exists():
            return candidate
        idx += 1


def main() -> int:
    args = parse_args()
    root = Path(args.root).resolve()
    mapping_path = Path(args.mapping)
    report_path = Path(args.report)
    report_path.parent.mkdir(parents=True, exist_ok=True)

    results = {"mode": args.mode, "moved": [], "skipped": [], "errors": []}

    with mapping_path.open("r", newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    for row in rows:
        action = row.get("action", "move")
        old_path = row.get("old_path", "").strip()
        new_path = row.get("new_path", "").strip()

        src = root / old_path
        dst = root / new_path

        if action != "move":
            results["skipped"].append({"row": row, "reason": f"unsupported_action:{action}"})
            continue

        if not src.exists():
            results["skipped"].append({"row": row, "reason": "source_missing"})
            continue

        target = unique_destination(dst)
        entry = {
            "old_path": old_path,
            "new_path": str(target.relative_to(root)),
            "action": action,
        }

        if args.mode == "dry-run":
            results["moved"].append(entry)
            continue

        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(src), str(target))
            results["moved"].append(entry)
        except Exception as exc:  # pragma: no cover - defensive
            entry["error"] = str(exc)
            results["errors"].append(entry)

    report_path.write_text(json.dumps(results, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"mode: {args.mode}")
    print(f"moved: {len(results['moved'])}")
    print(f"skipped: {len(results['skipped'])}")
    print(f"errors: {len(results['errors'])}")
    print(f"report: {report_path}")
    return 0 if not results["errors"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
